#测试Git
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.8.83:8066/EQUSER?useSSL=false
    username: root
    password: master
    type: com.zaxxer.hikari.HikariDataSource
