spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.8.83:8066/jf_vmdb?useSSL=false
    username: bguseradm
    password: jiafeng20170573
    type: com.zaxxer.hikari.HikariDataSource
